//! Per-project Traefik file-provider entries under
//! `~/.config/henk/dynamic/<slug>.yml`.
//!
//! Each linked project gets exactly one YAML file containing one router
//! and one service per host. Traefik's file provider watches the dir
//! and reloads on change without a restart.

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::consts::{HENK_FILE_HEADER, PROJECT_MANIFEST_VERSION, PROXY_NETWORK};
use crate::detect::backend;
use crate::project::manifest::{HostEntry, ProjectManifest, ProjectMode};
use crate::stack::paths;

/// Path to the file-provider YAML for `slug`.
pub fn entry_path(slug: &str) -> Result<PathBuf> {
    Ok(paths::config_dir()?
        .join("dynamic")
        .join(format!("{slug}.yml")))
}

/// Render and write the file-provider YAML for the given manifest.
/// Atomic + idempotent (skips the write when content matches what's
/// already on disk).
pub fn write(manifest: &ProjectManifest) -> Result<()> {
    let path = entry_path(&manifest.slug)?;
    let parent = path
        .parent()
        .context("dynamic dir path must have a parent")?;
    fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;

    let body = render(manifest);
    if let Ok(existing) = fs::read_to_string(&path)
        && existing == body
    {
        return Ok(());
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).with_context(|| format!("writing {}", tmp.display()))?;
    fs::rename(&tmp, &path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Remove the file-provider entry for `slug` (used by `henk unlink`).
pub fn remove(slug: &str) -> Result<()> {
    let path = entry_path(slug)?;
    if path.exists() {
        fs::remove_file(&path).with_context(|| format!("removing {}", path.display()))?;
    }
    Ok(())
}

/// Rewrite any project entry that predates the current rendering — one still
/// pointing straight at a `loadBalancer` (no health check, no error-page
/// fallback), or one with no `-http` router (so http:// requests fall through to
/// the catchall and get told, wrongly, that the project isn't linked).
///
/// Without this, everything linked before those changes keeps the old behaviour
/// forever: `.henk.toml` lives inside each project and henk keeps no global index
/// of where those projects are, so nothing else would ever re-render these files.
/// We reconstruct the manifest from the entry itself — the per-host `target` is
/// all `render` needs.
pub fn migrate_legacy_entries() -> Result<Vec<String>> {
    let dyn_dir = paths::config_dir()?.join("dynamic");
    if !dyn_dir.exists() {
        return Ok(Vec::new());
    }

    let mut migrated = Vec::new();
    for entry in fs::read_dir(&dyn_dir).with_context(|| format!("reading {}", dyn_dir.display()))? {
        let path = entry?.path();
        if path.extension().and_then(|s| s.to_str()) != Some("yml") {
            continue;
        }
        let Some(slug) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        // `_henk.yml` is the stack's own dashboard / TLS config.
        if slug.starts_with('_') {
            continue;
        }
        let body = fs::read_to_string(&path).unwrap_or_default();
        let is_current = body.contains("failover:") && body.contains("henk-https-redirect");
        if is_current {
            continue;
        }
        let Some(manifest) = manifest_from_entry(slug, &body) else {
            continue;
        };
        write(&manifest)?;
        migrated.push(slug.to_string());
    }
    Ok(migrated)
}

/// Rebuild a manifest from a rendered entry. Only what `render` reads has to
/// survive the round-trip: the hosts, in order, each with its backend as an
/// explicit `target`. Mode is therefore irrelevant — `target` always wins.
fn manifest_from_entry(slug: &str, body: &str) -> Option<ProjectManifest> {
    let hosts: Vec<HostEntry> = backend::parse_linked_hosts(slug, body)
        .into_iter()
        .map(|linked| HostEntry {
            host: linked.host.clone(),
            service: None,
            port: None,
            target: Some(linked.url),
            health_path: None,
            // Preserve the vite sub-host's router name (`<slug>-vite`).
            flags: if linked.host.starts_with("vite.") {
                vec!["vite".to_string()]
            } else {
                vec![]
            },
        })
        .collect();
    if hosts.is_empty() {
        return None;
    }
    Some(ProjectManifest {
        schema_version: PROJECT_MANIFEST_VERSION,
        slug: slug.to_string(),
        mode: ProjectMode::Host,
        hosts,
    })
}

fn render(manifest: &ProjectManifest) -> String {
    let mut out = String::new();
    out.push_str(HENK_FILE_HEADER);
    out.push_str("\n# Generated by `henk` for project ");
    out.push_str(&manifest.slug);
    out.push_str(" — see ");
    out.push_str(".henk.toml in the project. Hand-edits are overwritten.\n\n");

    out.push_str("http:\n  routers:\n");
    for (i, host) in manifest.hosts.iter().enumerate() {
        let router_name = router_name(&manifest.slug, host, i);
        out.push_str(&format!("    {router_name}:\n"));
        out.push_str(&format!("      rule: \"Host(`{}`)\"\n", host.host));
        out.push_str("      entryPoints:\n        - websecure\n");
        out.push_str("      tls: {}\n");
        out.push_str(&format!("      service: {router_name}\n"));

        // The same host on :80, redirected to https. This is deliberately a
        // per-host router rather than a redirect on the `web` entrypoint: an
        // entrypoint-wide redirect also catches hostnames that aren't linked at
        // all, bouncing them to https where the certificate can't cover them —
        // a typo would fail the TLS handshake instead of reaching the "nothing
        // is linked" page. Redirecting only the hosts henk actually knows about
        // leaves :80 free for the catchall to answer readably.
        out.push_str(&format!("    {router_name}-http:\n"));
        out.push_str(&format!("      rule: \"Host(`{}`)\"\n", host.host));
        out.push_str("      entryPoints:\n        - web\n");
        out.push_str("      middlewares:\n        - henk-https-redirect\n");
        out.push_str(&format!("      service: {router_name}\n"));
    }

    out.push_str("  services:\n");
    for (i, host) in manifest.hosts.iter().enumerate() {
        let svc_name = router_name(&manifest.slug, host, i);
        let main = format!("{svc_name}-main");
        let url = backend_url(manifest, host);

        // The router points at a `failover` service: while the real backend is
        // healthy it serves it; when the backend is down/unreachable Traefik
        // routes to `henk-error-pages` (defined in the stack's dynamic config)
        // so the visitor gets a branded "site unavailable" page instead of a raw
        // 502 Bad Gateway. The `errors` middleware can't cover this case — it
        // only catches error *responses* a live backend returns, not a dead one.
        out.push_str(&format!("    {svc_name}:\n"));
        out.push_str("      failover:\n");
        out.push_str(&format!("        service: {main}\n"));
        out.push_str("        fallback: henk-error-pages\n");

        // The real backend, with an active health check that drives the failover.
        // The probed path must return 2xx/3xx or Traefik counts the backend as
        // down — apps that 401/404 on `/` set `health_path` in `.henk.toml`.
        out.push_str(&format!("    {main}:\n"));
        out.push_str("      loadBalancer:\n");
        out.push_str("        healthCheck:\n");
        out.push_str(&format!("          path: \"{}\"\n", host.health_path()));
        out.push_str("          interval: \"10s\"\n");
        out.push_str("          timeout: \"3s\"\n");
        out.push_str("        servers:\n");
        out.push_str(&format!("          - url: \"{url}\"\n"));
    }
    out
}

/// Stable router/service name. Service names with dots (Sail's
/// `laravel.test`) are normalised to dashes — Traefik label slugs can't
/// contain dots in the obvious places.
fn router_name(slug: &str, host: &HostEntry, index: usize) -> String {
    if host.flags.iter().any(|f| f == "vite") {
        return format!("{slug}-vite");
    }
    if index == 0 {
        return slug.to_string();
    }
    // For additional non-vite hosts, derive a suffix from the host's
    // leading label, e.g. `api.spatiebalk.test` → `spatiebalk-api`.
    let leading = host
        .host
        .split('.')
        .next()
        .unwrap_or("alt")
        .replace('.', "-");
    format!("{slug}-{leading}")
}

/// Build the backend URL Traefik talks to for this host.
///
/// Per-host `target` always wins when set — that lets docker-mode
/// projects route an individual sub-host to the host machine (typical
/// for Vite running on the host while the rest of the stack lives in
/// containers, where Docker holds the published port and forces Vite
/// to bind via `host.docker.internal`).
///
/// Otherwise: Docker mode resolves the container's service name on
/// `henk-proxy`; Host mode falls back to `host.docker.internal:80`.
fn backend_url(manifest: &ProjectManifest, host: &HostEntry) -> String {
    if let Some(target) = host.target.as_deref() {
        return target.to_string();
    }
    match manifest.mode {
        ProjectMode::Docker => {
            // Compose v2 aliases the service onto each network the
            // container joins. Since we add `henk-proxy` as a network,
            // the service name resolves there. Service names with dots
            // (Sail's `laravel.test`) DO resolve as DNS names.
            let svc = host.service.as_deref().unwrap_or("web");
            let port = host.port.unwrap_or(80);
            let _ = PROXY_NETWORK; // keep the import alive; caller logs on this
            format!("http://{svc}:{port}")
        }
        ProjectMode::Host => "http://host.docker.internal:80".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::manifest::ProjectMode;

    #[test]
    fn legacy_entry_regains_failover_health_check_and_router_names() {
        // A file rendered before the failover work: router straight at a
        // loadBalancer. Re-rendering it must keep every host and router name
        // stable while adding the health check and the error-page fallback.
        let legacy = r#"
http:
  routers:
    spatiebalk:
      rule: "Host(`spatiebalk.test`)"
      service: spatiebalk
    spatiebalk-vite:
      rule: "Host(`vite.spatiebalk.test`)"
      service: spatiebalk-vite
  services:
    spatiebalk:
      loadBalancer:
        servers:
          - url: "http://laravel.test:80"
    spatiebalk-vite:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"
"#;
        let manifest = manifest_from_entry("spatiebalk", legacy).expect("parses");
        let out = render(&manifest);

        assert!(out.contains("    spatiebalk:\n"), "router name preserved");
        assert!(
            out.contains("    spatiebalk-vite:\n"),
            "vite router name preserved"
        );
        assert!(out.contains("http://laravel.test:80"), "backend preserved");
        assert!(out.contains("http://host.docker.internal:5173"));
        assert!(out.contains("fallback: henk-error-pages"));
        assert!(out.contains("healthCheck:"));
    }

    #[test]
    fn migration_reports_no_hosts_for_an_unparseable_entry() {
        assert!(manifest_from_entry("broken", "not: a router file").is_none());
    }

    fn docker_manifest_with_host_and_vite() -> ProjectManifest {
        ProjectManifest {
            schema_version: 1,
            slug: "spatiebalk".into(),
            mode: ProjectMode::Docker,
            hosts: vec![
                HostEntry {
                    host: "spatiebalk.test".into(),
                    service: Some("laravel.test".into()),
                    port: Some(80),
                    target: None,
                    health_path: None,
                    flags: vec![],
                },
                HostEntry {
                    host: "vite.spatiebalk.test".into(),
                    service: Some("laravel.test".into()),
                    port: Some(5173),
                    target: None,
                    health_path: None,
                    flags: vec!["vite".into()],
                },
            ],
        }
    }

    #[test]
    fn docker_mode_renders_routers_and_services() {
        let m = docker_manifest_with_host_and_vite();
        let out = render(&m);
        assert!(out.contains("# managed by henk"));
        assert!(out.contains("Host(`spatiebalk.test`)"));
        assert!(out.contains("Host(`vite.spatiebalk.test`)"));
        // Two routers + two services
        assert!(out.contains("    spatiebalk:\n"));
        assert!(out.contains("    spatiebalk-vite:\n"));
        // Backend URLs: service name on the shared network, under the `-main`
        // primary that the failover wraps.
        assert!(out.contains("http://laravel.test:80"));
        assert!(out.contains("http://laravel.test:5173"));
        // Each router service is a failover → error-pages, with a health-checked
        // primary, so a down backend serves the branded page (not a raw 502).
        assert!(out.contains("failover:"), "router service is a failover");
        assert!(out.contains("fallback: henk-error-pages"));
        assert!(
            out.contains("    spatiebalk-main:\n"),
            "health-checked primary"
        );
        assert!(out.contains("healthCheck:"));
    }

    #[test]
    fn every_host_also_gets_an_http_router_that_redirects_to_https() {
        // Without this, `curl http://spatiebalk.test` matches no router and gets
        // Traefik's bare 404 — even with the app healthy. It has to be per-host
        // rather than an entrypoint-wide redirect, or unlinked hosts get bounced
        // to https too and die on the certificate instead of reaching the
        // "nothing is linked" page.
        let out = render(&docker_manifest_with_host_and_vite());
        assert!(out.contains("    spatiebalk-http:\n"));
        assert!(out.contains("    spatiebalk-vite-http:\n"));
        assert_eq!(
            out.matches("- henk-https-redirect").count(),
            2,
            "one redirect per linked host"
        );
        assert_eq!(
            out.matches("- web\n").count(),
            2,
            "the http routers listen on :80"
        );
    }

    #[test]
    fn host_mode_renders_host_docker_internal_backend() {
        let m = ProjectManifest {
            schema_version: 1,
            slug: "sparkle".into(),
            mode: ProjectMode::Host,
            hosts: vec![HostEntry {
                host: "sparkle.test".into(),
                service: None,
                port: None,
                target: Some("http://host.docker.internal:3000".into()),
                health_path: None,
                flags: vec![],
            }],
        };
        let out = render(&m);
        assert!(out.contains("http://host.docker.internal:3000"));
        assert!(out.contains("Host(`sparkle.test`)"));
    }

    #[test]
    fn additional_host_gets_leading_label_suffix() {
        let m = ProjectManifest {
            schema_version: 1,
            slug: "hub".into(),
            mode: ProjectMode::Docker,
            hosts: vec![
                HostEntry {
                    host: "hub.test".into(),
                    service: Some("hub".into()),
                    port: Some(8055),
                    target: None,
                    health_path: None,
                    flags: vec![],
                },
                HostEntry {
                    host: "mail.hub.test".into(),
                    service: Some("mailhog".into()),
                    port: Some(8025),
                    target: None,
                    health_path: None,
                    flags: vec![],
                },
            ],
        };
        let out = render(&m);
        assert!(out.contains("    hub:\n"));
        assert!(out.contains("    hub-mail:\n"));
        assert!(out.contains("http://mailhog:8025"));
    }
}
