//! Per-project Traefik file-provider entries under
//! `~/.config/henk/dynamic/<slug>.yml`.
//!
//! Each linked project gets exactly one YAML file containing one router
//! and one service per host. Traefik's file provider watches the dir
//! and reloads on change without a restart.

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

use crate::consts::{HENK_FILE_HEADER, PROXY_NETWORK};
use crate::project::manifest::{HostEntry, ProjectManifest, ProjectMode};
use crate::stack::paths;

/// Path to the file-provider YAML for `slug`.
pub fn entry_path(slug: &str) -> Result<PathBuf> {
    Ok(paths::config_dir()?.join("dynamic").join(format!("{slug}.yml")))
}

/// Render and write the file-provider YAML for the given manifest.
/// Atomic + idempotent (skips the write when content matches what's
/// already on disk).
pub fn write(manifest: &ProjectManifest) -> Result<()> {
    let path = entry_path(&manifest.slug)?;
    let parent = path.parent().context("dynamic dir path must have a parent")?;
    fs::create_dir_all(parent)
        .with_context(|| format!("creating {}", parent.display()))?;

    let body = render(manifest);
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == body {
            return Ok(());
        }
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).with_context(|| format!("writing {}", tmp.display()))?;
    fs::rename(&tmp, &path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(())
}

/// Remove the file-provider entry for `slug` (used by `henk unlink`).
pub fn remove(slug: &str) -> Result<()> {
    let path = entry_path(slug)?;
    if path.exists() {
        fs::remove_file(&path)
            .with_context(|| format!("removing {}", path.display()))?;
    }
    Ok(())
}

fn render(manifest: &ProjectManifest) -> String {
    let mut out = String::new();
    out.push_str(HENK_FILE_HEADER);
    out.push_str("\n# Generated by `henk` for project ");
    out.push_str(&manifest.slug);
    out.push_str(" — see ");
    out.push_str(".henk.toml in the project. Hand-edits are overwritten.\n\n");

    out.push_str("http:\n  routers:\n");
    for (i, host) in manifest.hosts.iter().enumerate() {
        let router_name = router_name(&manifest.slug, host, i);
        out.push_str(&format!("    {router_name}:\n"));
        out.push_str(&format!("      rule: \"Host(`{}`)\"\n", host.host));
        out.push_str("      entryPoints:\n        - websecure\n");
        out.push_str("      tls: {}\n");
        out.push_str(&format!("      service: {router_name}\n"));
    }

    out.push_str("  services:\n");
    for (i, host) in manifest.hosts.iter().enumerate() {
        let svc_name = router_name(&manifest.slug, host, i);
        out.push_str(&format!("    {svc_name}:\n"));
        out.push_str("      loadBalancer:\n        servers:\n");
        let url = backend_url(manifest, host);
        out.push_str(&format!("          - url: \"{url}\"\n"));
    }
    out
}

/// Stable router/service name. Service names with dots (Sail's
/// `laravel.test`) are normalised to dashes — Traefik label slugs can't
/// contain dots in the obvious places.
fn router_name(slug: &str, host: &HostEntry, index: usize) -> String {
    if host.flags.iter().any(|f| f == "vite") {
        return format!("{slug}-vite");
    }
    if index == 0 {
        return slug.to_string();
    }
    // For additional non-vite hosts, derive a suffix from the host's
    // leading label, e.g. `api.spatiebalk.test` → `spatiebalk-api`.
    let leading = host
        .host
        .split('.')
        .next()
        .unwrap_or("alt")
        .replace('.', "-");
    format!("{slug}-{leading}")
}

/// Build the backend URL Traefik talks to for this host.
///
/// Per-host `target` always wins when set — that lets docker-mode
/// projects route an individual sub-host to the host machine (typical
/// for Vite running on the host while the rest of the stack lives in
/// containers, where Docker holds the published port and forces Vite
/// to bind via `host.docker.internal`).
///
/// Otherwise: Docker mode resolves the container's service name on
/// `henk-proxy`; Host mode falls back to `host.docker.internal:80`.
fn backend_url(manifest: &ProjectManifest, host: &HostEntry) -> String {
    if let Some(target) = host.target.as_deref() {
        return target.to_string();
    }
    match manifest.mode {
        ProjectMode::Docker => {
            // Compose v2 aliases the service onto each network the
            // container joins. Since we add `henk-proxy` as a network,
            // the service name resolves there. Service names with dots
            // (Sail's `laravel.test`) DO resolve as DNS names.
            let svc = host.service.as_deref().unwrap_or("web");
            let port = host.port.unwrap_or(80);
            let _ = PROXY_NETWORK; // keep the import alive; caller logs on this
            format!("http://{svc}:{port}")
        }
        ProjectMode::Host => "http://host.docker.internal:80".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::manifest::ProjectMode;

    fn docker_manifest_with_host_and_vite() -> ProjectManifest {
        ProjectManifest {
            schema_version: 1,
            slug: "spatiebalk".into(),
            mode: ProjectMode::Docker,
            hosts: vec![
                HostEntry {
                    host: "spatiebalk.test".into(),
                    service: Some("laravel.test".into()),
                    port: Some(80),
                    target: None,
                    flags: vec![],
                },
                HostEntry {
                    host: "vite.spatiebalk.test".into(),
                    service: Some("laravel.test".into()),
                    port: Some(5173),
                    target: None,
                    flags: vec!["vite".into()],
                },
            ],
        }
    }

    #[test]
    fn docker_mode_renders_routers_and_services() {
        let m = docker_manifest_with_host_and_vite();
        let out = render(&m);
        assert!(out.contains("# managed by henk"));
        assert!(out.contains("Host(`spatiebalk.test`)"));
        assert!(out.contains("Host(`vite.spatiebalk.test`)"));
        // Two routers + two services
        assert!(out.contains("    spatiebalk:\n"));
        assert!(out.contains("    spatiebalk-vite:\n"));
        // Backend URLs: service name on the shared network
        assert!(out.contains("http://laravel.test:80"));
        assert!(out.contains("http://laravel.test:5173"));
    }

    #[test]
    fn host_mode_renders_host_docker_internal_backend() {
        let m = ProjectManifest {
            schema_version: 1,
            slug: "sparkle".into(),
            mode: ProjectMode::Host,
            hosts: vec![HostEntry {
                host: "sparkle.test".into(),
                service: None,
                port: None,
                target: Some("http://host.docker.internal:3000".into()),
                flags: vec![],
            }],
        };
        let out = render(&m);
        assert!(out.contains("http://host.docker.internal:3000"));
        assert!(out.contains("Host(`sparkle.test`)"));
    }

    #[test]
    fn additional_host_gets_leading_label_suffix() {
        let m = ProjectManifest {
            schema_version: 1,
            slug: "hub".into(),
            mode: ProjectMode::Docker,
            hosts: vec![
                HostEntry {
                    host: "hub.test".into(),
                    service: Some("hub".into()),
                    port: Some(8055),
                    target: None,
                    flags: vec![],
                },
                HostEntry {
                    host: "mail.hub.test".into(),
                    service: Some("mailhog".into()),
                    port: Some(8025),
                    target: None,
                    flags: vec![],
                },
            ],
        };
        let out = render(&m);
        assert!(out.contains("    hub:\n"));
        assert!(out.contains("    hub-mail:\n"));
        assert!(out.contains("http://mailhog:8025"));
    }
}
