//! Generate the `compose.override.yml` (or fallback `henk.override.yml`)
//! that joins the project's web service to the shared `henk-proxy`
//! network so Traefik can reach it.
//!
//! With the M3-refit file-provider architecture, the override file
//! carries ONLY network membership — no Traefik labels. Routing rules
//! live in `~/.config/henk/dynamic/<slug>.yml` (see `file_provider.rs`).
//!
//! This is the smallest non-destructive footprint we can have on a
//! user's project: a sibling YAML, header-tagged, and a single line in
//! `.env` (with consent) for any port-collision case.

use anyhow::{Context, Result, bail};
use std::fs;
use std::path::{Path, PathBuf};

use crate::consts::{HENK_FILE_HEADER, PROXY_NETWORK};

/// Names compose auto-merges, in priority order. The first one that
/// already exists short-circuits us into the fallback path.
const COMPOSE_OVERRIDE_NAMES: &[&str] = &[
    "compose.override.yaml",
    "compose.override.yml",
    "docker-compose.override.yaml",
    "docker-compose.override.yml",
];

const HENK_OVERRIDE_NAME: &str = "henk.override.yml";

/// Result of choosing where to write our override.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OverrideTarget {
    /// User has no `compose.override.yml` etc. We write `compose.override.yml`
    /// directly; Compose auto-merges it.
    Canonical(PathBuf),
    /// User already has a `compose.override.yml` we shouldn't touch. We
    /// write `henk.override.yml` and the caller asks the user to add a
    /// `COMPOSE_FILE=...` line to `.env` so Compose picks both up.
    Fallback {
        path: PathBuf,
        existing_canonical: PathBuf,
    },
}

/// Pick which override path to write into for a project at `dir`.
///
/// We only fall back to `henk.override.yml` when a *foreign*
/// `compose.override.yml` (or sibling) is on disk. If the existing
/// canonical override carries our header, it's safe to overwrite — and
/// safer than producing two override files (which need a `COMPOSE_FILE`
/// env line to be picked up together).
pub fn pick_target(dir: &Path) -> OverrideTarget {
    for name in COMPOSE_OVERRIDE_NAMES {
        let p = dir.join(name);
        if !p.exists() {
            continue;
        }
        let body = fs::read_to_string(&p).unwrap_or_default();
        if body.contains(HENK_FILE_HEADER) {
            // Our own file — keep using it.
            return OverrideTarget::Canonical(p);
        }
        return OverrideTarget::Fallback {
            path: dir.join(HENK_OVERRIDE_NAME),
            existing_canonical: p,
        };
    }
    OverrideTarget::Canonical(dir.join(COMPOSE_OVERRIDE_NAMES[1]))
}

/// One service whose container needs to join the shared `henk-proxy`
/// network. `existing_networks` are whatever the service already
/// belonged to in the user's compose — we preserve them.
#[derive(Debug, Clone)]
pub struct ServiceMembership {
    pub service: String,
    pub existing_networks: Vec<String>,
}

/// Render the YAML body that joins each member service to the
/// `henk-proxy` network. Multi-service projects (hub-style with
/// `hub` + `mailhog`) need every routed service on the network, not
/// just the main one.
pub fn render(members: &[ServiceMembership]) -> String {
    let mut out = String::new();
    out.push_str(HENK_FILE_HEADER);
    out.push_str("\n# Generated by `henk` — DO NOT remove the network membership.\n");
    out.push_str("# Routing rules live in ~/.config/henk/dynamic/<slug>.yml.\n");
    out.push_str("# Hand-edits to this file are overwritten on `henk link`.\n\n");

    out.push_str("services:\n");
    for m in members {
        out.push_str(&format!("  {}:\n", m.service));
        out.push_str("    networks:\n");
        let mut emitted = 0usize;
        for n in &m.existing_networks {
            if !n.is_empty() && n != PROXY_NETWORK {
                out.push_str(&format!("      - {n}\n"));
                emitted += 1;
            }
        }
        if emitted == 0 {
            // Compose's "default" network is implicit. Re-name it so
            // the service still has its private network for
            // service-to-service calls inside the project.
            out.push_str("      - default\n");
        }
        out.push_str(&format!("      - {PROXY_NETWORK}\n"));
    }

    out.push_str("\nnetworks:\n");
    out.push_str(&format!("  {PROXY_NETWORK}:\n"));
    out.push_str("    external: true\n");
    out
}

/// Write the override file for the given service memberships into
/// `dir`, picking the canonical or fallback path automatically.
pub fn write(dir: &Path, members: &[ServiceMembership]) -> Result<OverrideTarget> {
    let target = pick_target(dir);
    let path = match &target {
        OverrideTarget::Canonical(p) => p.clone(),
        OverrideTarget::Fallback { path, .. } => path.clone(),
    };
    let body = render(members);
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == body {
            return Ok(target);
        }
        if !existing.contains(HENK_FILE_HEADER) {
            bail!(
                "{} already exists and is not managed by henk — refusing to overwrite",
                path.display()
            );
        }
    }
    let tmp = path.with_extension("tmp");
    fs::write(&tmp, body).with_context(|| format!("writing {}", tmp.display()))?;
    fs::rename(&tmp, &path)
        .with_context(|| format!("renaming {} -> {}", tmp.display(), path.display()))?;
    Ok(target)
}

/// Delete the override file (used by `henk unlink`). Only deletes the
/// file if it carries our header — never touches a foreign override.
pub fn remove(dir: &Path) -> Result<()> {
    for candidate in COMPOSE_OVERRIDE_NAMES
        .iter()
        .chain(std::iter::once(&HENK_OVERRIDE_NAME))
    {
        let p = dir.join(candidate);
        if !p.exists() {
            continue;
        }
        let body = fs::read_to_string(&p).unwrap_or_default();
        if body.contains(HENK_FILE_HEADER) {
            fs::remove_file(&p).with_context(|| format!("removing {}", p.display()))?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn picks_canonical_when_no_override_exists() {
        let dir = TempDir::new().unwrap();
        match pick_target(dir.path()) {
            OverrideTarget::Canonical(p) => {
                assert_eq!(p.file_name().unwrap(), "compose.override.yml");
            }
            other => panic!("expected Canonical, got {other:?}"),
        }
    }

    #[test]
    fn reuses_canonical_when_existing_override_is_ours() {
        let dir = TempDir::new().unwrap();
        std::fs::write(
            dir.path().join("compose.override.yml"),
            format!("{HENK_FILE_HEADER}\nservices: {{}}\n"),
        )
        .unwrap();
        match pick_target(dir.path()) {
            OverrideTarget::Canonical(p) => {
                assert_eq!(p.file_name().unwrap(), "compose.override.yml");
            }
            other => panic!("expected Canonical (our own file), got {other:?}"),
        }
    }

    #[test]
    fn falls_back_to_henk_override_when_compose_override_exists() {
        let dir = TempDir::new().unwrap();
        std::fs::write(dir.path().join("compose.override.yml"), "# user file").unwrap();
        match pick_target(dir.path()) {
            OverrideTarget::Fallback {
                path,
                existing_canonical,
            } => {
                assert_eq!(path.file_name().unwrap(), "henk.override.yml");
                assert_eq!(
                    existing_canonical.file_name().unwrap(),
                    "compose.override.yml"
                );
            }
            other => panic!("expected Fallback, got {other:?}"),
        }
    }

    fn one(service: &str, nets: &[&str]) -> Vec<ServiceMembership> {
        vec![ServiceMembership {
            service: service.into(),
            existing_networks: nets.iter().map(|s| s.to_string()).collect(),
        }]
    }

    #[test]
    fn render_preserves_existing_networks_and_appends_henk_proxy() {
        let body = render(&one("laravel.test", &["sail"]));
        assert!(body.contains("# managed by henk"));
        assert!(body.contains("services:\n  laravel.test:\n"));
        assert!(body.contains("- sail"));
        assert!(body.contains("- henk-proxy"));
        assert!(body.contains("external: true"));
    }

    #[test]
    fn render_falls_back_to_default_network_when_none_listed() {
        let body = render(&one("web", &[]));
        assert!(body.contains("- default"));
        assert!(body.contains("- henk-proxy"));
    }

    #[test]
    fn render_emits_every_service_when_multi_service() {
        let members = vec![
            ServiceMembership {
                service: "hub".into(),
                existing_networks: vec![],
            },
            ServiceMembership {
                service: "mailhog".into(),
                existing_networks: vec![],
            },
        ];
        let body = render(&members);
        assert!(body.contains("  hub:\n"));
        assert!(body.contains("  mailhog:\n"));
        // henk-proxy is appended once per service plus declared once.
        assert_eq!(body.matches("- henk-proxy").count(), 2);
    }

    #[test]
    fn write_refuses_to_overwrite_foreign_override() {
        let dir = TempDir::new().unwrap();
        // Force fallback path to be the one with content.
        std::fs::write(dir.path().join("henk.override.yml"), "# someone else's").unwrap();
        // Force fallback by also creating a canonical override.
        std::fs::write(dir.path().join("compose.override.yml"), "# theirs").unwrap();

        let err = write(dir.path(), &one("web", &[])).unwrap_err();
        assert!(format!("{err}").contains("not managed by henk"));
    }
}
